name: Auto-Merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Auto-approve Dependabot PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        uses: fastify/github-action-merge-dependabot@v3.11.2
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: major
          merge-method: squash      # options: merge, squash, rebase
          # use-github-auto-merge: true
          # approve-only: false
          
