# name: Dependabot Auto Merge

# on:
#   pull_request:
#     types: [opened, synchronize, reopened, ready_for_review]
#   workflow_dispatch:

# permissions:
#   contents: write
#   pull-requests: write
#   checks: read

# jobs:
#   dependabot-auto-merge:
#     runs-on: ubuntu-latest
#     # Run only for Dependabot (includes the legacy preview bot)
#     if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}

#     # Put secrets in job env so steps can reference them easily
#     env:
#       AUTOMERGE_PAT: ${{ secrets.AUTOMERGE_PAT }}
#       # Toggle to 'true' if you want the workflow to auto-approve Dependabot PRs before enabling auto-merge
#       AUTO_APPROVE: 'false'

#     steps:
#       # Quick debug info (prints PR number / actor)
#       - name: Debug PR info
#         run: |
#           echo "Actor=$GITHUB_ACTOR"
#           echo "Event=$GITHUB_EVENT_NAME"
#           echo "PR_NUMBER=${{ github.event.pull_request.number }}"
#           echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}"
      
#       - name: Fetch Dependabot metadata
#         id: meta
#         uses: dependabot/fetch-metadata@v2
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}

#       # Optional: Auto-approve the PR (useful when branch protection requires review)
#       # Enable by setting env AUTO_APPROVE: 'true' above (and ensure the PAT user has permission to approve)
#       - name: Auto-approve Dependabot PR (optional)
#         if: ${{ env.AUTO_APPROVE == 'true' }}
#         uses: hmarr/auto-approve-action@v3
#         with:
#           github-token: ${{ env.AUTOMERGE_PAT }}
#         # no id needed; this just posts an approval so branch protection checks that require approvals are satisfied

#       - name: Enable auto-merge (peter-evans)
#         uses: peter-evans/enable-pull-request-automerge@v3
#         env:
#           # GH_TOKEN is required for any gh CLI calls the action performs internally
#           GH_TOKEN: ${{ env.AUTOMERGE_PAT }}
#         with:
#           token: ${{ env.AUTOMERGE_PAT }}
#           pull-request-number: ${{ github.event.pull_request.number }}
#           merge-method: squash

#       - name: Confirm (log)
#         run: |
#           echo "Requested auto-merge for PR #${{ github.event.pull_request.number }} (actor=${GITHUB_ACTOR})"
